#' Check TMB is Working
#'
#' Check that the installation of TMB is working before trying
#' to run any VAST models.
#'
#' @details
#' This function will generate a lot of output to your screen that
#' can be helpful when trying to troubleshoot the installation of
#' Rtools40. Most importantly, you can see the location of where
#' your computer is trying to find make files. If you have already run this
#' function on your computer, then you should see
#' \code{"make: Nothing to be done for 'all'"}.
#'
#' @return A single integer is returned, where zero means that
#' your installation of Rtools40 and TMB is good to go. I hope you get a zero!
#' If the status is failed, then you will see \code{"Compilation failed"},
#' a stop message generated by \code{\link[TMB]{compile}}.
#' @export
#' @author Kelli Faye Johnson
#' @examples
#' check_TMB()
#'
check_TMB <- function() {
  packages <- utils::installed.packages()
  stopifnot("TMB" %in% packages[, "Package"])

  wd <- getwd()
  on.exit(setwd(wd), add = TRUE)
  setwd(system.file("examples", package = "TMB"))
  test <- TMB::compile("simple.cpp")
  return(test)
}
