#' Complete general diagnostic for West Coast VAST run.
#'
#' Output figures and tables to the disk specific to a given index
#' of abundance generated by \code{\link[VAST]}. The code is specific
#' to data collected by the Northwest Fisheries Science Center
#' Bottom Trawl Survey.
#'
#' @param data The raw data, though special column names are needed.
#' @param rep The Report as generated by code{Obj$report()}
#' @param TmbData The data used to fit the model and generated by
#' \code{\link[VAST]{Data_Fn}}
#' @param Opt Output from \code{\link[TMBhelper]{Optimize}}
#' @param dir The directory that you want to save the results to.
#' Do not include a trailing slash. The default is your current directory.
#' @param Method The method defining how space was represented in the model.
#' Options include \code{c("Mesh", "Grid", "Spherical_mesh")}.
#' @param grid_size_km The grid size used if \code{Method = "Grid"}.
#' @param randomseed Control value for the K-means algorithm
#' when \code{Methods = "Mesh"}.
#' @param nstart Control value for the K-means algorithm
#' when \code{Methods = "Mesh"}.
#' @param iter.max Control value for the K-means algorithm
#' when \code{Methods = "Mesh"}.
#'
#' @author Kelli Faye Johnson
#'
vast_wc_diag_plot <- function(data, rep, TmbData, Opt,
  dir = getwd(),
  Method = c("Mesh", "Grid", "Spherical_mesh"),
  grid_size_km = 25,
  randomseed = 1, nstart = 100, iter.max = 1e3) {

  #### Checks before running any code
  if (!"Year" %in% colnames(data)) stop("Year must be a column of data")
  if (!file.exists(dir)) stop("The directory, ", dir, " does not exist.")
  Method <- match.arg(Method, choices = c("Mesh", "Grid", "Spherical_mesh"),
    several.ok = FALSE)
  if (Method == "Grid" & is.null(grid_size_km)) stop("A grid size in km",
    " must be supplied if Method = 'Grid'")

  #### Which years to plot
  Year_Set <- seq(min(data[, "Year"]),max(data[, "Year"]))
  Years2Include <- which(Year_Set %in% sort(unique(data[, "Year"])))

  n_x <- TmbData$n_x

  e_list <- SpatialDeltaGLMM::Prepare_Extrapolation_Data_Fn(
    Region = "California_current",
    strata.limits = data.frame(
      "STRATA" = c("Coastwide","CA","OR","WA"),
      "north_border" = c(49.0, 42.0, 46.0, 49.0),
      "south_border" = c(32.0, 32.0, 42.0, 46.0),
      "shallow_border" = c(55, 55, 55, 55),
      "deep_border" = c(1280, 1280, 1280, 1280)
    )
  )

  Spatial_List <- SpatialDeltaGLMM::Spatial_Information_Fn(
    grid_size_km = grid_size_km,
    n_x = n_x,
    Method = Method,
    Lon = data[, "Lon"], Lat = data[, "Lat"],
    Extrapolation_List = e_list,
    randomseed = randomseed,
    nstart = nstart,
    iter.max = iter.max,
    DirPath = dir, Save_Results = FALSE)

  # Get region-specific settings for plots
  MapDetails_List <- SpatialDeltaGLMM::MapDetails_Fn(
    Region = "California_current",
    NN_Extrap = Spatial_List$PolygonList$NN_Extrap,
    Extrapolation_List = e_list)

  #Plot Anisotropy
  SpatialDeltaGLMM::PlotAniso_Fn(
    FileName = file.path(dir, "Aniso.png"),
    Report = rep, TmbData = TmbData)

  # Annual density surface, use plot_set = 3 to start and then do plot_set=c(3:10) to see more output on a good working model
  SpatialDeltaGLMM::PlotResultsOnMap_Fn(plot_set = 3,
    MappingDetails = MapDetails_List[["MappingDetails"]],
    Report = rep, Sdreport = Opt$SD,
    PlotDF = MapDetails_List[["PlotDF"]],
    MapSizeRatio = MapDetails_List[["MapSizeRatio"]],
    Xlim = MapDetails_List[["Xlim"]],
    Ylim = MapDetails_List[["Ylim"]],
    FileName = dir, Year_Set = Year_Set,
    Years2Include = Years2Include, Rotate = MapDetails_List[["Rotate"]],
    Cex = MapDetails_List[["Cex"]], Legend = MapDetails_List[["Legend"]],
    zone = MapDetails_List[["Zone"]],
    mar = c(0, 0, 2, 0), oma = c(3.5, 3.5, 0, 0),
    cex = 1.8, plot_legend_fig = FALSE)

  #index of abundance
  Index <- SpatialDeltaGLMM::PlotIndex_Fn(
    DirName = dir,
    TmbData = TmbData, Sdreport = Opt[["SD"]],
    Year_Set = Year_Set, Years2Include = Years2Include,
    strata_names = strata.limits[, 1], use_biascorr = TRUE)
  # Creates a table of index values same as what is output from the above code
  # pander::pandoc.table(
  #   Index$Table[, c("Year","Fleet","Estimate_metric_tons","SD_log","SD_mt")])

  # center of gravity / range expansion
  SpatialDeltaGLMM::Plot_range_shifts(
    Report = rep, TmbData = TmbData, Sdreport = Opt[["SD"]],
    Znames = colnames(TmbData$Z_xm), PlotDir = dir, Year_Set = Year_Set)

  ################
  # Make diagnostic plots
  ################

  SpatialDeltaGLMM::Plot_data_and_knots(
    Extrapolation_List = e_list,
    Spatial_List = Spatial_List, Data_Geostat = data, PlotDir = dir)

  #convergence
  # pander::pandoc.table(
  #   Opt$diagnostics[, c("Param","Lower","MLE","Upper","final_gradient")])
  write.table(file = file.path(dir, "convergence.csv"),
    x = Opt$diagnostics[, c("Param","Lower","MLE","Upper","final_gradient")],
    row.names = FALSE, sep = ",")

  # Plot encounter probability diagnostics p/a
  Enc_prob <- SpatialDeltaGLMM::Check_encounter_prob(
    Report = rep, Data_Geostat = data, DirName = dir)

  # QQ plot
  Q <- SpatialDeltaGLMM::QQ_Fn(
    TmbData = TmbData, Report = rep, save_dir = dir,
    FileName_PP = "Posterior_Predictive",
    FileName_Phist = "Posterior_Predictive-Histogram",
    FileName_QQ = "Q-Q_plot", FileName_Qhist="Q-Q_hist")[[1]]

  # Residuals
  SpatialDeltaGLMM::plot_residuals(Lat_i = data[,"Lat"], Lon_i = data[,"Lon"], TmbData = TmbData, Report = rep, Q = Q, savedir = dir,
    MappingDetails = MapDetails_List[["MappingDetails"]],
    PlotDF = MapDetails_List[["PlotDF"]],
    MapSizeRatio = MapDetails_List[["MapSizeRatio"]],
    Xlim = MapDetails_List[["Xlim"]], Ylim = MapDetails_List[["Ylim"]],
    FileName = NULL,
    Year_Set = Year_Set, Years2Include = Years2Include,
    Rotate = MapDetails_List[["Rotate"]],
    Cex = MapDetails_List[["Cex"]], Legend = MapDetails_List[["Legend"]],
    zone = MapDetails_List[["Zone"]],
    mar = c(0, 0, 2, 0), oma = c(3.5, 3.5, 0, 0), cex = 1.8)

}


